---
title: "Frederick Thielen's CV"
author: Frederick Thielen
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1NzJ4jrrtCueDpe1YwKsyroiWSsas_R4top_YPiLKHeg/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

```

Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at my github account. Repo: data_driven_cv")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/fthielen/data_driven_cv/thielen_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```


Digital competencies {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

Language skills {#lang}
--------------------------------------------------------------------------------
```{r}
CV %>% print_skill_bars(type = "language")
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/nstrayer/cv](https://github.com/fthielen/data_driven_cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Frederick Thielen {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Current positions {data-icon=laptop-file data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('current')
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Working Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```


Honours & Awards {data-icon=award}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('honours_awards')
```



Selected publications as first author {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('academic_articles_aside')
```
:::

```{r}
CV %<>% print_section('academic_articles')
```


Selected publications as last author {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('academic_articles_last_aside')
```
:::

```{r}
CV %<>% print_section('academic_articles_last')
```



```{r}
CV %<>% print_links()
```
